#acl LeoSimons:read,write,admin,delete,revert AdminGroup:read,write All:read
#format plain
#
# This page is pulled from the general wiki. To add spam terms for the entire wiki farm,
# edit http://wiki.apache.org/general/LocalBadContent.
#
# This page can contain additional items not in the BadContent database.
# But please only add terms here if they apply to the entire Apache wiki farm.

##++Apache/LocalBadContent
\.gradhome\.com
\.sex-portal\.us
\.webcamss\.com
100freemb\.com
168bc\.com
24h\.msn\.hm
741\.com
9cy\.com
angelcities\.com
bj-yctd\.com
blog-city\.com
bodybuilding
bravepages\.com
buyyourall\.com
chatsky\.cn
dreamstation\.com
dunky\.info
easyday\.cn
electronic-wire\.com
envy\.nu
eseo\.cn
eukhost\.com
exactpages\.com
fcpages\.com
feeltime\.cn
feeltime\.com
freecities\.com
freewebpages\.org
freewebsitehosting\.com
g0g\.net
hbgm\.cn
hfire\.cn
homepage\.mac\.com
honey99\.cn
honey99\.com
ibnsites\.com
ihotmusic
isas\.com\.cn
kogaryu\.com
lo\.lee\.tv
masterjin\.com
mathsolutions\.50webs\.com
mnsp\.cn
nekoo\.cn
oa8000\.com\.cn
o-f\.com
paisi\.com
paisidesign\.com
seorj\.cn
sfzone\.cn
sh-dzbc\.com\.cn
shyxbc\.com\.cn
smbay\.cn
tiffanyonsale\.org
tnb120\.com\.cn
tunfar\.com\.cn
u-tokyo\.ac\.jp
vergleich-riester-rente\.net
wm-u\.com
wtcsites\.com
x2\.top\.tc
x25\.us\.to
xcyouth\.org\.cn
xn--lnakuten-9za\.se
yehuo\.cn
zjeyu\.com
zx\.slave\.ca
zyseo\.com
##--Apache/LocalBadContent
